apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2-deployment
  template:
    metadata:
      labels:
        app: lab2-deployment
    spec:
      containers:
      - name: deployment
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_USERNAME
            value: Lev Logvinov
          - name: REACT_APP_COMPANY_NAME
            value: llogvinov
