apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lab3
spec:
  tls:
  - hosts:
    - kavabanga-fqdn.com
    secretName: app-tls
  rules:
  - host: kavabanga-fqdn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-lab3
            port:
              number: 3000